-- Plain-SQL equivalent of prisma/seed.ts, for pasting into a SQL editor
-- that isn't reachable via Prisma Client (e.g. no raw Postgres access from
-- the environment running the seed). Same data, same idempotency (ON
-- CONFLICT ... DO UPDATE instead of Prisma's upsert). IDs are hand-assigned
-- readable strings, not cuid()s — cuid() is generated by Prisma Client at
-- insert time, not a Postgres function, so a plain SQL insert needs its
-- own id values. Nothing in the schema requires ids to look like cuids.
--
-- Safe to re-run.

-- Domains
INSERT INTO "Domain" (id, key, label) VALUES
  ('dom_physical', 'physical', 'Physical'),
  ('dom_digital', 'digital', 'Digital')
ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label;

-- Submarkets (physical)
INSERT INTO "Submarket" (id, key, label, "domainId") VALUES
  ('sub_plumbing', 'plumbing', 'Plumbing', 'dom_physical'),
  ('sub_electrical', 'electrical', 'Electrical', 'dom_physical'),
  ('sub_cleaning', 'cleaning', 'Cleaning', 'dom_physical'),
  ('sub_carpentry', 'carpentry', 'Carpentry', 'dom_physical'),
  ('sub_painting', 'painting', 'Painting', 'dom_physical'),
  ('sub_appliance-repair', 'appliance-repair', 'Appliance Repair', 'dom_physical'),
  ('sub_moving-logistics', 'moving-logistics', 'Moving & Logistics', 'dom_physical'),
  ('sub_gardening-landscaping', 'gardening-landscaping', 'Gardening & Landscaping', 'dom_physical'),
  ('sub_event-setup', 'event-setup', 'Event Setup', 'dom_physical'),
  ('sub_in-person-tutoring', 'in-person-tutoring', 'In-Person Tutoring', 'dom_physical'),
-- Submarkets (digital)
  ('sub_web-development', 'web-development', 'Web Development', 'dom_digital'),
  ('sub_graphic-design', 'graphic-design', 'Graphic Design', 'dom_digital'),
  ('sub_content-writing', 'content-writing', 'Content Writing', 'dom_digital'),
  ('sub_video-editing', 'video-editing', 'Video Editing', 'dom_digital'),
  ('sub_social-media-management', 'social-media-management', 'Social Media Management', 'dom_digital'),
  ('sub_virtual-assistant', 'virtual-assistant', 'Virtual Assistant', 'dom_digital'),
  ('sub_data-entry', 'data-entry', 'Data Entry', 'dom_digital'),
  ('sub_online-tutoring', 'online-tutoring', 'Online Tutoring', 'dom_digital'),
  ('sub_voice-over', 'voice-over', 'Voice Over', 'dom_digital'),
  ('sub_transcription', 'transcription', 'Transcription', 'dom_digital')
ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label, "domainId" = EXCLUDED."domainId";

-- Client types
INSERT INTO "ClientTypeRef" (id, key, label) VALUES
  ('ctype_individual', 'individual', 'Individual'),
  ('ctype_corporate', 'corporate', 'Corporate'),
  ('ctype_ngo', 'ngo', 'NGO'),
  ('ctype_government', 'government', 'Government')
ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label;
